# -*- coding: utf-8 -*-
"""CLASE 8-/08/09/22

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cuh5TPx6KrX5xl-98qFWcEFpR2iXxMDU

#**COLEGIO SIGLO XXI- EL SOCORRO**
#**PRESENTANDO A: ING PAOLA ANDREA QUINTERO**
#**PRESENTADO POR: ZHARYD VANESSA QUIROGA ESPINOSA**
#**8 SEPTIEMPRE 2022**

#**¿Qué es Pyton?**
# Python es un lenguaje de alto nivel de programación interpretado cuya filosofía hace hincapié en la legibilidad de su código, se utiliza para desarrollar aplicaciones de todo tipo, ejemplos: Instagram, Netflix, Spotify, Panda 3D, entre otros.

#**Fecha de lanzamiento:**1991
#Creadores:Guido van Rossum

#**Recuperado de:** https://www.cursosaula21.com/que-es-python/
## Nueva sección
"""

print("esto es una suma")
numero_uno=16
numero_dos=4
resultado = numero_uno + numero_dos
print(resultado)



print("esto es una resta")
numero_uno=16
numero_dos=4
resultado = numero_uno - numero_dos
print(resultado)



print("esto es una multiplicacion")
numero_uno=5
numero_dos=4
resultado = numero_uno * numero_dos
print(resultado)



print("esto es una division ")
numero_uno=80
numero_dos=4
resultado = numero_uno / numero_dos
print(resultado)

"""#Ejercicios de Tipos de Datos simples 
nombre = input ("¿Cómo te llamas?")

"""

nombre=input("¿Cómo te llamas ?")

"""##Ejercicio1
Escribir un programa que pregunte el nombre del usuario en la consola de un número entero e imprima por pantalla en líneas distintad el nombre del usuario tantas veces como el número introducido.
"""

nombre= input ("¿Cómo te llamas?")
n= input("introduce un número entero:")
print((nombre+"\n")*int(n))

"""##Ejercicio2
Escribir un programa que le pida al usuario su peso(en kg)y estatura (en metros), calcule el índice de masa corporal y lo almacene en una variable, e imprima por pantalla la frase 'Tu índice de masa corporal es <imc>' donde <imc> es el índice de masa  corporal calculando redondeado conm los decimales
"""

peso = input("¿cual es tu peso en KG?")
estatura = input("¿cual es tu estatura en M?")
imc = round(float(peso)/float(estatura)**2,2)
print("tu indice de masa corporal es " + str(imc))

"""## **LÍBRERIAS EN PHYTON**
# ¿Que es?:
##En este sentido, una librería es un conjunto de archivos que se utiliza para desarrollar software. Suele estar compuesta de código y datos, y su fin es ser utilizada por otros programas de forma totalmente autónoma. Simple y llanamente, es un archivo importable.
"""